// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJrQx9KjdExYsDm2-YxY-dU-a_yAbWTf4',
    appId: '1:915767292819:web:e15aca57bdc6f14f6eee66',
    messagingSenderId: '915767292819',
    projectId: 'travel-care-hackatho',
    authDomain: 'travel-care-hackatho.firebaseapp.com',
    storageBucket: 'travel-care-hackatho.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClSP9NZT1hsQRnhN03M12Mc9fKKbJ08j0',
    appId: '1:915767292819:android:90e6b343a1c4aec16eee66',
    messagingSenderId: '915767292819',
    projectId: 'travel-care-hackatho',
    storageBucket: 'travel-care-hackatho.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASDHeijZltdvrgv78yrXJqS02iFc9W4UI',
    appId: '1:915767292819:ios:2a63d34d34f76b496eee66',
    messagingSenderId: '915767292819',
    projectId: 'travel-care-hackatho',
    storageBucket: 'travel-care-hackatho.appspot.com',
    iosBundleId: 'com.example.travelCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASDHeijZltdvrgv78yrXJqS02iFc9W4UI',
    appId: '1:915767292819:ios:2a63d34d34f76b496eee66',
    messagingSenderId: '915767292819',
    projectId: 'travel-care-hackatho',
    storageBucket: 'travel-care-hackatho.appspot.com',
    iosBundleId: 'com.example.travelCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJrQx9KjdExYsDm2-YxY-dU-a_yAbWTf4',
    appId: '1:915767292819:web:6669d21a709e29456eee66',
    messagingSenderId: '915767292819',
    projectId: 'travel-care-hackatho',
    authDomain: 'travel-care-hackatho.firebaseapp.com',
    storageBucket: 'travel-care-hackatho.appspot.com',
  );
}
